project:
  type: website
  output-dir: docs
website:
  title: "JKD Blog"
  navbar:
    right:
      - text: "Archive"
        href: archive.qmd
      - text: "About"
        href: about.qmd
      - icon: github
        href: https://jitendradhiman.github.io/
      - icon: linkedin
        href: https://www.linkedin.com/in/jitendra-kumar-dhiman-phd-b02462a0/
      # - icon: twitter
      #   href: https://twitter.com
# format:
#   html:
#     theme: sandstone
#     css: styles.css
# google-analytics: <Insert your ID here>
format:
  html:
    theme: 
     light: [cosmo,  theme.scss]
     dark:  [darkly, theme.scss]
    toc: true
    toc-location: left
    toc-depth: 3
    code-fold: true
  utterances:
    repo: Jitendradhiman/jkdblog  # Replace with your actual repo
    issue-term: title                   # Use post title for issues
    label: "💬"                         # Optional label for issues
    theme: "github-light"               # Choose a theme